---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.diff$

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.1.0
    hooks:
      - id: codespell

  - repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.2.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/amperser/proselint.git
    rev: 0.10.2
    hooks:
      - id: proselint
        types: [plain-text]
        exclude: LICENSE

  - repo: https://gitlab.com/devopshq/gitlab-ci-linter.git
    rev: v1.0.3
    hooks:
      - id: gitlab-ci-linter
        args:
          - "--server"
          - https://git.shore.co.il

  - repo: https://git.shore.co.il/nimrod/yamltool.git
    rev: v0.1.2
    hooks:
      - id: yamltool

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup.git
    rev: v1.0.1
    hooks:
      - id: rst-linter

  - repo: https://github.com/myint/rstcheck.git
    rev: v5.0.0
    hooks:
      - id: rstcheck

  - repo: https://github.com/ambv/black.git
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - |
            --line-length=79

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--filter-files", "--profile", "black"]

  - repo: https://github.com/PyCQA/prospector.git
    rev: 1.7.7
    hooks:
      - id: prospector
        args:
          - |-
            --max-line-length=79
          - |-
            --with-tool=pyroma
          - |-
            --with-tool=bandit
          - |-
            --without-tool=pep257
          - |-
            --doc-warnings
          - |-
            --test-warnings
          - |-
            --full-pep8
          - |-
            --strictness=high
          - |-
            --no-autodetect
        additional_dependencies:
          - bandit
          - pyroma

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - |-
            --doctests
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-loopy
          - flake8-pie
          - flake8-tuple
          - flake8-warnings

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety.git
    rev: v1.2.4
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/asottile/pyupgrade.git
    rev: v2.32.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/hadialqattan/pycln.git
    rev: v1.3.2
    hooks:
      - id: pycln

  - repo: https://github.com/PyCQA/docformatter.git
    rev: v1.4
    hooks:
      - id: docformatter

  - repo: https://github.com/mgedmin/check-manifest.git
    rev: '0.48'
    hooks:
      - id: check-manifest
